export { HomePage } from './HomePage'
export { EventsPage } from './EventsPage'
export { HowItWorksPage } from './HowItWorksPage'
export { AboutPage } from './AboutPage'
export { SignUpPage } from './SignUpPage'
export { LoginPage } from './LoginPage'
